<?php
#$wgShowExceptionDetails = true;
#error_reporting( -1 );
#ini_set( 'display_errors', 1 );
#$wgDebugLogFile="/tmp/log";
# This file was automatically generated by the MediaWiki 1.35.7
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
   exit;
}
require_once __DIR__ . '/etc/config.php';

$wgNamespaceRobotPolicies[NS_USER] = 'noindex';
$wgNamespaceRobotPolicies[NS_USER_TALK] = 'noindex';
$wgNamespaceRobotPolicies[NS_SPECIAL] = 'noindex';

$wgScriptPath = "";
$wgScriptExtension = ".php";
$wgArticlePath = "/w/$1";
$wgUsePathInfo = true;
$wgFavicon = "/public/favicon.ico";
$wgResourceBasePath = $wgScriptPath;

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "support@mooncell.wiki";
$wgPasswordSender = "support@mooncell.wiki";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

$wgPasswordReminderResendTime = 12;

$wgDefaultUserOptions['enotifwatchlistpages'] = 0;

## Database settings
$wgDBtype = "mysql";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## To enable image uploads, make sure the 'images' directory
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";
$wgLocalisationCacheConf["store"] = "array";
# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh-cn";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "知识共享署名-非商业性使用-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

$wgAutoConfirmAge = 7 * 24 * 60 * 60;
$wgAutoConfirmCount = 30;

$wgNamespacesWithSubpages[NS_MAIN] = true;

$wgAllowUserCss = true;
$wgAllowUserJs = true;
$wgAllowSiteCSSOnRestrictedPages = true;
$wgAllowImageTag = true;
$wgAllowExternalImages = false;
$wgEnableImageWhitelist = true;
$wgRestrictDisplayTitle = false;
$wgForcedRawSMaxage = 3600;

# 缩略图最大允许 6000px * 6000px (36000000pixels)
$wgMaxImageArea = 3.6e7;
$wgMaxAnimatedGifArea = 3.6e7;

$wgJobRunRate = 0.05;
$wgRunJobsAsync = true;
$wgUpdateRowsPerJob = 50;

$wgUsePrivateIPs = true;

$wgHiddenPrefs[] = 'nickname';

$wgResourceLoaderMaxage = [
   'versioned' => 30 * 24 * 60 * 60, // 30 days
   'unversioned' => 60 * 60, // 60 minutes
];

$wgImportSources = array(
   'wikipedia' => array('ja', 'en', 'zh'),
   'wikispecies',
   'wikia' => array('fategrandorder'),
);

$wgHooks['SkinTemplateOutputPageBeforeExec'][] = function ($sk, &$tpl) {
   $tpl->set('appinfo', $sk->footerLink('appinfo', 'appinfolink'));
   $tpl->data['footerlinks']['places'][] = 'appinfo';
   return true;
};

$wgHooks['SkinTemplateOutputPageBeforeExec'][] = function ($sk, &$tpl) {
   $tpl->set('ads', $sk->footerLink('ads', 'adslink'));
   $tpl->data['footerlinks']['places'][] = 'ads';
   return true;
};

$wgHooks['SkinTemplateOutputPageBeforeExec'][] = function ($sk, &$tpl) {
   $tpl->set('comment', $sk->footerLink('comment', 'commentlink'));
   $tpl->data['footerlinks']['places'][] = 'comment';
   return true;
};

$wgFooterIcons['poweredby']['mooncellproject'] = [
   "src" => "/images/project1.png",
   "url" => "//project.mooncell.wiki",
   "alt" => "a Mooncell project",
   "height" => "31",
   "width" => "88",
];

# RIGHTS
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['upload'] = false; // Allow regular users to upload files
$wgGroupPermissions['user']['move-rootuserpages'] = false; // can move root userpages
$wgGroupPermissions['user']['move-categorypages'] = false;
$wgGroupPermissions['user']['suppressredirect'] = true;
$wgGroupPermissions['user']['delete'] = false;
$wgGroupPermissions['user']['reupload-shared'] = false;
$wgGroupPermissions['user']['movefile'] = false;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['move-subpages'] = false;
$wgGroupPermissions['user']['reupload'] = false;
$wgGroupPermissions['user']['suppressredirect'] = false;
$wgGroupPermissions['user']['sendemail'] = false;
$wgGroupPermissions['user']['changetags'] = false;
$wgGroupPermissions['user']['editcontentmodel'] = false;

$wgGroupPermissions['autoconfirmed']['editsemiprotected'] = true;
$wgGroupPermissions['autoconfirmed']['upload'] = true;
$wgGroupPermissions['autoconfirmed']['reupload-shared'] = true;
$wgGroupPermissions['autoconfirmed']['move-subpages'] = true;
$wgGroupPermissions['autoconfirmed']['suppressredirect'] = true;
$wgGroupPermissions['autoconfirmed']['delete'] = true;
$wgGroupPermissions['autoconfirmed']['reupload-shared'] = true;
$wgGroupPermissions['autoconfirmed']['movefile'] = true;
$wgGroupPermissions['autoconfirmed']['move'] = true;
$wgGroupPermissions['autoconfirmed']['move-subpages'] = true;
$wgGroupPermissions['autoconfirmed']['reupload'] = true;
$wgGroupPermissions['autoconfirmed']['suppressredirect'] = true;
$wgGroupPermissions['autoconfirmed']['sendemail'] = false;
$wgGroupPermissions['autoconfirmed']['changetags'] = false;
$wgGroupPermissions['autoconfirmed']['editcontentmodel'] = false;

$wgGroupPermissions['Angestellter']['upload'] = true;
$wgGroupPermissions['Angestellter']['reupload-shared'] = true;
$wgGroupPermissions['Angestellter']['move-subpages'] = true;
$wgGroupPermissions['Angestellter']['suppressredirect'] = true;
$wgGroupPermissions['Angestellter']['delete'] = true;
$wgGroupPermissions['Angestellter']['reupload-shared'] = true;
$wgGroupPermissions['Angestellter']['movefile'] = true;
$wgGroupPermissions['Angestellter']['move'] = true;
$wgGroupPermissions['Angestellter']['move-subpages'] = true;
$wgGroupPermissions['Angestellter']['reupload'] = true;
$wgGroupPermissions['Angestellter']['suppressredirect'] = true;
$wgGroupPermissions['Angestellter']['sendemail'] = false;
$wgGroupPermissions['Angestellter']['changetags'] = false;
$wgGroupPermissions['Angestellter']['editcontentmodel'] = false;
$wgGroupPermissions['Angestellter']['editsemiprotected'] = true;
$wgGroupPermissions['Angestellter']['autoconfirmed'] = true;

$wgGroupPermissions['Inspektor']['avataradmin'] = true;
$wgGroupPermissions['Inspektor']['commentadmin-restricted'] = true;

// Permission to change new' group assignments
$wgGroupPermissions['Editor']['move'] = true;
$wgGroupPermissions['Editor']['move-subpages'] = true;
$wgGroupPermissions['Editor']['move-rootuserpages'] = true; // can move root userpages
$wgGroupPermissions['Editor']['move-categorypages'] = true;
$wgGroupPermissions['Editor']['movefile'] = true;
$wgGroupPermissions['Editor']['read'] = true;
$wgGroupPermissions['Editor']['edit'] = true;
$wgGroupPermissions['Editor']['createpage'] = true;
$wgGroupPermissions['Editor']['createtalk'] = true;
$wgGroupPermissions['Editor']['writeapi'] = true;
$wgGroupPermissions['Editor']['upload'] = true;
$wgGroupPermissions['Editor']['reupload'] = true;
$wgGroupPermissions['Editor']['reupload-shared'] = true;
$wgGroupPermissions['Editor']['minoredit'] = true;
$wgGroupPermissions['Editor']['purge'] = true;
$wgGroupPermissions['Editor']['sendemail'] = true;
$wgGroupPermissions['Editor']['applychangetags'] = true;
$wgGroupPermissions['Editor']['changetags'] = true;
$wgGroupPermissions['Editor']['editcontentmodel'] = true;
$wgGroupPermissions['Editor']['delete'] = true;

$wgGroupPermissions['Dominator']['userrights'] = false;
$wgGroupPermissions['Dominator']['noratelimit'] = true;
$wgGroupPermissions['Dominator']['renameuser'] = true;
$wgGroupPermissions['Dominator']['interwiki'] = true;
$wgGroupPermissions['Dominator']['maintenance'] = true;
$wgGroupPermissions['Dominator']['deletelogentry'] = true;
$wgGroupPermissions['Dominator']['deleterevision'] = true;
$wgGroupPermissions['Dominator']['hideuser'] = true;
$wgGroupPermissions['Dominator']['suppressrevision'] = true;
$wgGroupPermissions['Dominator']['suppressionlog'] = true;

$wgGroupPermissions['sysop']['deleterevision'] = false;

$wgGroupPermissions['bureaucrat']['interwiki'] = true;
$wgGroupPermissions['bureaucrat']['maintenance'] = true;
$wgGroupPermissions['bureaucrat']['suppressrevision'] = true;
$wgGroupPermissions['bureaucrat']['suppressionlog'] = true;
$wgGroupPermissions['bureaucrat']['hideuser'] = true;
$wgGroupPermissions['bureaucrat']['deletelogentry'] = true;
$wgGroupPermissions['bureaucrat']['deleterevision'] = true;

$wgAddGroups['Dominator'] = array('interface-admin', 'sysop', 'bot', 'Editor', 'checkuser', 'smwadministrator', 'smwcurator', 'widgeteditor', 'Angestellter', 'Inspektor');
$wgRemoveGroups['Dominator'] = array('interface-admin', 'sysop', 'bot', 'Editor', 'checkuser', 'smwadministrator', 'smwcurator', 'widgeteditor', 'Angestellter', 'Inspektor');

$wgExternalLinkTarget = '_blank';


# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin('MonoBook');
wfLoadSkin('Timeless');
wfLoadSkin('Vector');
wfLoadSkin('Citizen');

wfLoadExtension('Cargo');
$wgGroupPermissions['cargoadmin']['recreatecargodata'] = true;
wfLoadExtension('CategoryTree');
wfLoadExtension('Cite');
wfLoadExtension('CiteThisPage');
wfLoadExtension('CodeEditor');
wfLoadExtension('ConfirmEdit');
wfLoadExtension('ConfirmEdit/QuestyCaptcha');
$wgCaptchaTriggers['addurl'] = false;

wfLoadExtension('DataMaps');
$wgDataMapsReportTimingInfo = true;

wfLoadExtension('Gadgets');
$wgGroupPermissions['sysop']['gadgets-edit'] = true;
$wgGroupPermissions['sysop']['gadgets-definition-edit'] = true;
$wgGroupPermissions['Dominator']['gadgets-edit'] = true;
$wgGroupPermissions['Dominator']['gadgets-definition-edit'] = true;
wfLoadExtension('ImageMap');
wfLoadExtension('InputBox');
wfLoadExtension('Interwiki');
// wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension('Nuke');
wfLoadExtension('OATHAuth');
$wgGroupPermissions['user']['oathauth-enable'] = true;

wfLoadExtension('PageImages');
wfLoadExtension('ParserFunctions');
$wgPFEnableStringFunctions = true;

wfLoadExtension('PdfHandler');
wfLoadExtension('Poem');
wfLoadExtension('Renameuser');
wfLoadExtension('ReplaceText');
$wgGroupPermissions['bureaucrat']['replacetext'] = true;
wfLoadExtension('SecureLinkFixer');
wfLoadExtension('SpamBlacklist');
wfLoadExtension('SyntaxHighlight_GeSHi');
wfLoadExtension('TemplateData');
wfLoadExtension('TextExtracts');
wfLoadExtension('TitleBlacklist');
# Disabled due to unexpectedly high load
# wfLoadExtension( 'VisualEditor' );
wfLoadExtension('WikiEditor');
wfLoadExtension('Scribunto');
$wgScribuntoDefaultEngine = 'luasandbox';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;

# StructuredDiscussions
wfLoadExtension('Flow');

# CheckUser
wfLoadExtension('CheckUser');
$wgGroupPermissions['sysop']['checkuser'] = true;
$wgGroupPermissions['sysop']['checkuser-log'] = true;

# Variables
wfLoadExtension('Variables');

# RightFunctions
wfLoadExtension('RightFunctions');

# wfLoadExtension( 'RegexFunctions' );
require_once "$IP/extensions/RegexFun/RegexFun.php";

# Echo
wfLoadExtension('Echo');

# Echo
wfLoadExtension('Echo');
wfLoadExtension('Graph');
# Loops
wfLoadExtension('Loops');
$egLoopsCountLimit  = 800;

# AbuseFilter
wfLoadExtension('AbuseFilter');
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['*']['abusefilter-log-detail'] = true;
$wgGroupPermissions['*']['abusefilter-view'] = true;
$wgGroupPermissions['*']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-privatedetails'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;

# CodeMirror
wfLoadExtension('CodeMirror');
$wgDefaultUserOptions['usecodemirror'] = 1;
# Enable bracket matching in CodeMirror
$wgCodeMirrorEnableBracketMatching = true;
# Enable accessible colors in CodeMirror
$wgCodeMirrorAccessibilityColors = true;
# Enable line numbering in CodeMirror
# defaults to the template namespace [ NS_TEMPLATE ]
# null enables it for all namespace
# [] for disabling everywhere
$wgCodeMirrorLineNumberingNamespaces = null;

# JsonConfig
wfLoadExtension('JsonConfig');

# MassEditRegex
wfLoadExtension('MassEditRegex');
$wgGroupPermissions['sysop']['masseditregex'] = true;

# MsUpload
wfLoadExtension('MsUpload');
$wgMSU_useDragDrop = true; // Should the drag & drop area be shown? (Not set by default)
$wgMSU_showAutoCat = true; // Files uploaded while editing a category page will be added to that category
$wgMSU_checkAutoCat = true; // Whether the checkbox for adding a category to a page is checked by default
$wgMSU_useMsLinks = false; // Insert links in Extension:MsLinks style?
$wgMSU_confirmReplace = true; // Show the "Replace file?" checkbox
$wgMSU_imgParams = '400px'; // Any image parameter(s), delimited by pipes, e.g., {width}px, left, right, center, none, border, frameless, frame, thumb etc.
$wgEnableWriteAPI = true; // Enable the API
$wgEnableUploads = true; // Enable uploads
$wgAllowJavaUploads = true; // Solves problem with Office 2007 and newer files (docx, xlsx, etc.)
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'doc', 'xls', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx', 'pptx', 'gif', 'mp3', 'ogg', 'ogx', 'wav', 'csv', 'svg');
//$wgVerifyMimeType = false; // mw会觉得某些语音mimetype是application/php

# NativeSvgHandler
wfLoadExtension('NativeSvgHandler');

# Thanks
wfLoadExtension('Thanks');

# UniversalLanguageSelector
wfLoadExtension('UniversalLanguageSelector');
$wgULSLanguageDetection = false;
$wgULSIMEEnabled = false;
$wgMinervaAlwaysShowLanguageButton = false;

# VipsScaler
wfLoadExtension('VipsScaler');
$wgVipsCommand = "vips";
$wgVipsOptions = [
   // Sharpen jpeg files which are shrunk more than 1.2
   [
      'conditions' => [
         'mimeType' => 'image/jpeg',
         'minShrinkFactor' => 1.2,
      ],
      'sharpen' => ['radius' => 0, 'sigma' => 0.8],
   ],
   // Other jpeg files
   [
      'conditions' => [
         'mimeType' => 'image/jpeg',
      ],
      'sharpen' => false,
      'bilinear' => true,
   ],
   // Do a simple shrink for PNGs
   [
      'conditions' => [
         'mimeType' => 'image/png',
      ],
   ],
];
//https://www.mediawiki.org/wiki/Topic:Vvbnly9yfwjq6v0y
//1GiB
$wgMaxShellMemory = 1048576;


# WikiSEO
wfLoadExtension('WikiSEO');

# MobileFrontend
wfLoadExtension('MobileFrontend');
$wgDefaultMobileSkin = 'minerva';
$wgMFLazyLoadImages =   [
   // These will enable lazy loading images in beta mode
   'beta' => false,
   // These will enable lazy loading images in all modes
   'base' => false,
];
# $wgMFStopMobileRedirectCookieSecureValue = false;
# $wgMFExpandAllSectionsUserOption = true;
# $wgMFCollapseSectionsByDefault = false;
$wgMFAutodetectMobileView = false;
$wgMFMobileHeader = "X-Subdomain";
$wgMFEnableManifest = false;

# LabeledSectionTransclusion
wfLoadExtension('LabeledSectionTransclusion');

# MultiBoilerplate
wfLoadExtension('MultiBoilerplate');
$wgMultiBoilerplateDiplaySpecialPage = true;

# Tabber
# wfLoadExtension( 'Tabber' );
wfLoadExtension('TabberNeue');
#Maintenance
wfLoadExtension('Maintenance');

# DeleteUserPages
wfLoadExtension('DeleteUserPages');
$wgGroupPermissions['user']['delete-rootuserpages'] = true; // Let users delete their own user page and user talk page
$wgGroupPermissions['user']['delete-usersubpages'] = true; // Let users delete their own user subpages and associated talk pages

# Arrays 
wfLoadExtension('Arrays');

# Widgets
wfLoadExtension('Widgets');

# HeadScript
wfLoadExtension('HeadScript');

# MyVariables
wfLoadExtension('MyVariables');

# RevisionSlider
wfLoadExtension('RevisionSlider');

# CharInsert
wfLoadExtension('CharInsert');

# ContributionScores
wfLoadExtension('ContributionScores');
$wgContribScoreIgnoreBots = true;          // Exclude Bots from the reporting - Can be omitted.
$wgContribScoreIgnoreBlockedUsers = true;  // Exclude Blocked Users from the reporting - Can be omitted.
$wgContribScoresUseRealName = true;        // Use real user names when available - Can be omitted. Only for MediaWiki 1.19 and later.
$wgContribScoreDisableCache = false;       // Set to true to disable cache for parser function and inclusion of table.
//Each array defines a report - 7,50 is "past 7 days" and "LIMIT 50" - Can be omitted.
$wgContribScoreReports = array(
   array(7, 50),
   array(30, 50),
   array(0, 50)
);

# DeleteBatch
wfLoadExtension('DeleteBatch');
$wgGroupPermissions['bureaucrat']['deletebatch'] = false;
$wgGroupPermissions['sysop']['deletebatch'] = true;
wfLoadExtension('SemanticMediaWiki');
enableSemantics($wgCanonicalServer, true);
wfLoadExtension('SemanticResultFormats');
$smwgDVFeatures = ($smwgDVFeatures & ~SMW_DV_WPV_DTITLE);
$smwgQueryResultCacheType = CACHE_MEMCACHED;
$smwgQueryResultCacheLifetime = 60 * 60 * 24;
$smwgPageSpecialProperties[] = '_CDAT';

wfLoadExtension('TemplateStyles');

# VectorMenuSidebar
wfLoadExtension('VectorMenuSidebar');
$wgVectorMenuSidebar = true;
$wgEnableVMSCustomStyle = true;
$wgShowAfterMenuSidebar = true;

# Lazyload
wfLoadExtension('Lazyload');

# LanguageParser
wfLoadExtension('LanguageParser');

# PinyinSort
wfLoadExtension('PinyinSort');
$wgCategoryCollation = 'pinyin';

# PurgeAliyunCDN
wfLoadExtension('PurgeAliyunCDN');

# DynamicPageList3
wfLoadExtension('DynamicPageList3');

wfLoadSkin('MinervaNeue');

# ExternalData
wfLoadExtension('ExternalData');

# Elastica
#wfLoadExtension( 'Elastica' );

#wfLoadExtension( 'CirrusSearch' );
#$wgSearchType = 'CirrusSearch';
#$wgDisableSearchUpdate = true;

#AdvancedSearch
#wfLoadExtension( 'AdvancedSearch' );

wfLoadExtension('AWS');

require_once __DIR__ . '/etc/post-config.php';